name: CI Packages

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:

jobs:
  linux:
    name: Linux build/test + deb/rpm
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.ver.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Go mod tidy
        run: go mod tidy

      - name: Go test
        run: go test ./...

      - name: Build linux binary
        run: |
          mkdir -p dist
          go build -o dist/hellog ./cmd/hellog

      - name: Compute version
        id: ver
        shell: bash
        run: |
          ref="${GITHUB_REF#refs/tags/}"
          if [[ "$ref" == v* ]]; then
            echo "version=${ref#v}" >> "$GITHUB_OUTPUT"
          else
            echo "version=0.1.0" >> "$GITHUB_OUTPUT"
          fi

      - name: Set nfpm version in config
        shell: bash
        run: |
          sed -i "s/^version:.*/version: ${{ steps.ver.outputs.version }}/" packaging/nfpm.yaml

      - name: Install nfpm
        run: |
          go install github.com/goreleaser/nfpm/v2/cmd/nfpm@v2.33.1

      - name: Build deb
        run: |
          $(go env GOPATH)/bin/nfpm pkg --config packaging/nfpm.yaml --packager deb --target dist

      - name: Build rpm
        run: |
          $(go env GOPATH)/bin/nfpm pkg --config packaging/nfpm.yaml --packager rpm --target dist

      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          name: hellog-deb-${{ steps.ver.outputs.version }}
          path: |
            dist/*.deb
          if-no-files-found: error

      - name: Upload rpm packages
        uses: actions/upload-artifact@v4
        with:
          name: hellog-rpm-${{ steps.ver.outputs.version }}
          path: |
            dist/*.rpm
          if-no-files-found: error

  windows:
    name: Windows build/test + MSI
    runs-on: windows-latest
    outputs:
      version: ${{ steps.verwin.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Go mod tidy
        run: go mod tidy

      - name: Go test
        run: go test ./...

      - name: Build windows binary
        run: |
          New-Item -ItemType Directory -Force -Path dist | Out-Null
          go build -o dist/hellog.exe ./cmd/hellog

      - name: Compute version
        id: verwin
        shell: pwsh
        run: |
          if ($env:GITHUB_REF -like 'refs/tags/v*') {
            $ver = $env:GITHUB_REF -replace 'refs/tags/v',''
          } else {
            $ver = '0.1.0'
          }
          echo "version=$ver" >> $env:GITHUB_OUTPUT

      - name: Install WiX Toolset
        run: choco install -y wixtoolset

      - name: Build MSI with WiX
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path build | Out-Null
          # Compile .wxs to .wixobj
          candle "-dVersion=0.1.0" "-dBinPath=dist\hellog.exe" -out build\hellog.wixobj packaging\windows\hellog.wxs
          # Link to .msi
          light -ext WixUIExtension -o dist\hellog.msi build\hellog.wixobj

      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: hellog-msi-${{ steps.verwin.outputs.version }}
          path: |
            dist/hellog.msi
          if-no-files-found: error

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v4
        with:
          name: hellog-windows-exe-${{ steps.verwin.outputs.version }}
          path: |
            dist/hellog.exe
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [linux, windows, macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: hellog-*
          merge-multiple: true

      - name: Create GitHub Release and upload assets
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Hellog ${{ github.ref_name }}
          files: |
            dist/*.deb
            dist/*.rpm
            dist/hellog.msi
            dist/hellog.exe
            dist/hellog.pkg
  macos:
    name: macOS build/test + PKG
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
          cache: true

      - name: Go mod tidy
        run: go mod tidy

      - name: Go test
        run: go test ./...

      - name: Build darwin binary
        run: |
          mkdir -p dist
          go build -o dist/hellog ./cmd/hellog

      - name: Compute version
        id: vermac
        run: |
          ref="${GITHUB_REF#refs/tags/}"
          if [[ "$ref" == v* ]]; then
            echo "version=${ref#v}" >> "$GITHUB_OUTPUT"
          else
            echo "version=0.1.0" >> "$GITHUB_OUTPUT"
          fi

      - name: Build macOS pkg
        run: |
          # Prepare payload root
          mkdir -p pkgroot/usr/local/bin
          mkdir -p "pkgroot/Library/LaunchDaemons"
          mkdir -p "pkgroot/Library/Application Support/Hellog"
          cp dist/hellog pkgroot/usr/local/bin/hellog
          cp packaging/macos/hellog.plist "pkgroot/Library/LaunchDaemons/com.example.hellog.plist"
          # Install default config as .default (postinstall will copy on first install)
          cp packaging/config/config.json "pkgroot/Library/Application Support/Hellog/config.json.default"
          # Permissions
          chmod 0755 pkgroot/usr/local/bin/hellog
          chmod 0644 "pkgroot/Library/LaunchDaemons/com.example.hellog.plist"
          chmod 0644 "pkgroot/Library/Application Support/Hellog/config.json.default"
          # Scripts must be executable
          chmod +x packaging/macos/scripts/postinstall
          # Build pkg
          pkgbuild \
            --root pkgroot \
            --identifier com.example.hellog \
            --version "${{ steps.vermac.outputs.version }}" \
            --install-location / \
            --scripts packaging/macos/scripts \
            dist/hellog.pkg

      - name: Upload macOS pkg
        uses: actions/upload-artifact@v4
        with:
          name: hellog-macos-pkg-${{ steps.vermac.outputs.version }}
          path: dist/hellog.pkg
          if-no-files-found: error
